ifeq ($(TARGET_BOOTLOADER_BOARD_NAME), swift)

LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_PRELINK_MODULE := false
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/hw
LOCAL_SHARED_LIBRARIES := liblog libcutils
LOCAL_SRC_FILES += sensors_ak8973.c
LOCAL_MODULE := sensors.swift
LOCAL_MODULE_TAGS := optional
include $(BUILD_SHARED_LIBRARY)

endif